version: "3.8"

services:
  postgres:
    container_name: sol-postgres
    image: tegonhq/tegon-postgres:0.1.0-alpha
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sol

  # redis:
  #   image: redis:alpine3.19
  #   container_name: sol-redis
  #   networks:
  #     - sol
  #   ports:
  #     - 6379:6379
  #   restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:latest
    container_name: sol-qdrant
    restart: unless-stopped
    networks:
      - sol
    ports:
      - 6333:6333
      - 6334:6334
    volumes:
      - qdrant_data:/qdrant/storage

  # server:
  #   image: "redplanethq/server:${VERSION}"
  #   container_name: sol-server
  #   depends_on:
  #     - supertokens
  #     - redis
  #   restart: unless-stopped
  #   networks:
  #     - sol
  #   env_file:
  #     - .env
  #   environment:
  #     - DATABASE_URL=${DATABASE_URL}
  #     - FRONTEND_HOST=${FRONTEND_HOST}
  #     - BACKEND_HOST=${BACKEND_HOST}
  #     - OAUTH_CALLBACK_URL=${OAUTH_CALLBACK_URL}
  #     - SUPERTOKEN_CONNECTION_URI=${SUPERTOKEN_CONNECTION_URI}
  #     - POSTGRES_USER=${POSTGRES_USER}
  #     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  #     - POSTGRES_DB=${POSTGRES_DB}
  #     - DB_HOST=${DB_HOST}
  #     - DB_PORT=${DB_PORT}
  #     - DB_SCHEMA=${DB_SCHEMA}
  #     - REDIS_URL=${REDIS_URL}
  #     - REDIS_PORT=${REDIS_PORT}
  #     - BUCKET_NAME=${BUCKET_NAME}
  #     - GCP_SERVICE_ACCOUNT_FILE=${GCP_SERVICE_ACCOUNT_FILE}
  #     - PUBLIC_ATTACHMENT_URL=${PUBLIC_ATTACHMENT_URL}
  #   ports:
  #     - 5555:5555
  #     - 8001:3001
  #     - 8002:1234
  #   volumes:
  #     - ./certs:/app/apps/server/certs

  # webapp:
  #   image: "redplanethq/webapp:${VERSION}"
  #   container_name: sol-webapp
  #   restart: unless-stopped
  #   depends_on:
  #     - server
  #   networks:
  #     - sol
  #   environment:
  #     - BACKEND_URL=${BACKEND_URL}
  #     - NEXT_PUBLIC_BASE_HOST=${NEXT_PUBLIC_BASE_HOST}
  #     - NEXT_PUBLIC_VERSION=${VERSION}
  #     - NEXT_PUBLIC_BACKEND_HOST=${NEXT_PUBLIC_BACKEND_HOST}
  #     - NEXT_PUBLIC_POSTHOG_KEY=${NEXT_PUBLIC_POSTHOG_KEY}
  #     - NEXT_PUBLIC_POSTHOG_HOST=${NEXT_PUBLIC_POSTHOG_HOST}
  #     - NEXT_PUBLIC_SENTRY_DSN=${NEXT_PUBLIC_SENTRY_DSN}
  #     - NEXT_PUBLIC_NODE_ENV=${NODE_ENV}
  #     - NEXT_PUBLIC_CONTENT_HOST=${NEXT_PUBLIC_CONTENT_HOST}
  #     - NEXT_PUBLIC_TRIGGER_URL=${NEXT_PUBLIC_TRIGGER_URL}
  #   ports:
  #     - 8000:3000

volumes:
  qdrant_data:
  postgres_data:

networks:
  app_network:
    driver: bridge
  sol: {}
