version: "3.8"

services:
  postgres:
    container_name: sol-postgres
    image: redplanethq/postgres:0.1.0
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sol

  redis:
    image: redis:alpine3.19
    container_name: sol-redis
    networks:
      - sol
    ports:
      - 6379:6379
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:latest
    container_name: sol-qdrant
    restart: unless-stopped
    networks:
      - sol
    ports:
      - 6333:6333
      - 6334:6334
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  qdrant_data:
  postgres_data:

networks:
  app_network:
    driver: bridge
  sol: {}
