name: Build Docker Images

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  build-webapp:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: main

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Frontend Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: apps/webapp/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: tegonhq/sigma-webapp:${{ github.ref_name }}
          build-args: |
            SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}

  build-server:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: main

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Server Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: apps/server/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: tegonhq/sigma-server:${{ github.ref_name }}
